apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32355
      protocol: TCP
  selector:
    app: spring-boot-app
