apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8082            # Port exposed by the service
      targetPort: 8082      # Port your app listens on inside the container
      nodePort: 30082       # Optional: fixed NodePort (remove if you want a random one)

